# Generated by Django 5.2.8 on 2025-11-21 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date published',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 21, 21, 25, 30, 840329, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
